### ISSUE TITLE
Unique page views (based on referrer)

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#12]
This is requested a lot with our customers and we are going to build it. We just want to know how many people want this. We want to show unique page views based on browser referrer. This means we would see a visit from example.com to example.com/contact as 1 unique page view but if you close your tab and go to example.com again it will be seen as another unique page view. We don't want to use cookies or IP information to track users. This is the best privacy friendly solution.

### Tasks 
- [x] Update scripts to include a unique boolean
- [x] Update queue database to have the field
- [x] Update main database to have the field
- [x] Update the processing scripts to include the unique data
- [x] Expose unique page views in our API
- [ ] Update the UI to display the unique page views

**Comment by adriaanvanrossum** [comment]
Also via @lseelenbinder: Entry pages (For entry pages, I mean a way to see if a page was visited from via an internal link or external referral. This helps isolate how traffic flows into the site and through the site. Obviously this wouldn't be perfect since you're not tracking individual sessions)

**Comment by fertila** [comment]
Not sure if this might be the same. I would like to see referrers on a per page base in a given time frame.

**Comment by adriaanvanrossum** [comment]
It's many more related to this https://github.com/simpleanalytics/roadmap/issues/9?

> > Basically, it'd be helpful to see which referrals lead to which pages. That way I can see if searches are more likely to land on the home page or the pricing page, etc.
> 
> Thanks to dinkydani21 and lseelenbinder:
> 
> > Referrals by page; Basically, it'd be helpful to see which referrals lead to which pages. That way I can see if searches are more likely to land on the home page or the pricing page, etc

**Comment by adriaanvanrossum** [comment]
@Amritnagi is suggesting to use something like this, and I think it's great:

![telegram-cloud-photo-size-4-5951551627225837852-y](https://user-images.githubusercontent.com/1079135/69070548-e85d8980-0a5a-11ea-92c4-552c20fba41d.jpg)

**Comment by adriaanvanrossum** [comment]
- [x] Added the uniques to the processing scripts

It's deployed and available here: https://simpleanalytics.com/simpleanalytics.com.json

**Comment by adriaanvanrossum** [comment]
Deployed to production!
