### ISSUE TITLE
Update public script

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#309]
- [x] Add `utm_content` and `utm_term`
- [x] The error when skipping page view on localhost is wrong. It says `Simple Analytics: Not sending requests from undefined`
- [x] We need to know the original domain when overwritten (https://github.com/simpleanalytics/roadmap/issues/304)
- [x] Fix a bug in some IE11 `Object doesn't support property or method 'getRandomValues'`
- [x] Fix a bug in Android 4 `Cannot read property '0' of undefined`
- [x] It would be great to have callbacks in our events (https://github.com/simpleanalytics/roadmap/issues/295)
- [x] Minify the embed files again
- [x] Add source map with original files to the file (if easy)
- [x] Blacklist certain pages (simpleanalytics/roadmap#193)
- [x] Add navigator.language (simpleanalytics/roadmap#313)
- [x] Add screen size
- [x] Add current view port
- [x] Add disable autoTrack
- [x] Expose tracking page view

**Comment by adriaanvanrossum** [comment]
Done most of it in https://github.com/simpleanalytics/scripts/pull/9

**Comment by adriaanvanrossum** [comment]
Done all in simpleanalytics/scripts#9
