### ISSUE TITLE
Let customers allow certain URL params

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#569]
Sometimes URL params are crucial to a business. For example a product_id (`/product?product_id=1337`) on a product page. We don't record any query params at the moment, but let's add a feature where customers can allow certain URL params.

```html
<script data-allow-params="product_id,slug,active" src="https://scripts.simpleanalyticscdn.com/latest.js" />
```

With the above embed code we should do this:

|Visited URL |Saved URL  |
|:--- |:--- | 
|`https://example.com/product?product_id=1337&utm_source=company-x&data=show`|`https://example.com/product?product_id=1337&utm_source=company-x`|
|`https://example.com/product?user_id=9148&product_id=1337&ref=company-x`|`https://example.com/product?product_id=1337&ref=company-x`|

### Tasks

- [ ] Allow custom URL params in embed script
- [ ] Allow custom URL params in queue app
- [ ] Store custom URL params in a params object in Elasticsearch
- [ ] Show custom URL params in our dashboard (in the "Referrals" drop down menu)
- [ ] Allow search by custom URL params in our dashboard
- [ ] Allow to download custom URL params from our page view API
- [ ] Show custom URL params in our Stats API
- [ ] Allow search on custom URL params in our Stats API

**Comment by AdamXweb** [comment]
This is a good feature. Are UTM parameters currently being saved?
