### ISSUE TITLE
Optimize print version of our dashboard

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#591]
### Tasks

- [x] Remove dark mode toggle
- [x] Remove logo (or make less prominent)
- [x] Remove links to other pages
- [x] Remove footer (maybe add a [`noprint` class](https://www.arclab.com/en/kb/htmlcss/how-to-print-a-specific-part-of-a-html-page-css-media-screen-print.html)?)
- [x] Check if it works with new header
- [x] Show date and time of print moment (useful when having multiple prints)
- [x] Show period somewhere (start and end date)
- [x] Make sure to add page break [stackoverflow](https://stackoverflow.com/a/1664058/747044) (if somehow two pages happen)
- [ ] Add css page settings to [`@page`](https://developer.mozilla.org/en-US/docs/Web/CSS/@page)

### Tips 

- Chrome has a [render as print feature](https://iq.opengenus.org/using-css-to-print-html-webpage/)

<img width="935" alt="image" src="https://user-images.githubusercontent.com/1079135/120192437-c0ed9c80-c24d-11eb-8309-b00dd465035d.png">

**Comment by jibsaramnim** [comment]
> Show period somewhere (start and end date)

@adriaanvanrossum I think this is something that was also discussed for the non-print (so, normal) dashboard too, right? Some customers have also noted that with the new design it's not clear what actual date range is selected. Would it make sense to just change the way the period is shown, or do you want me to go ahead and make a print-specific-only something for this?

**Comment by adriaanvanrossum** [comment]
Yes. Add the date period to the dashboard itself would fix both

**Comment by adriaanvanrossum** [comment]
A few more fixes to the print version

- [ ] More horizontal space on top
- [ ] More horizontal space at the bottom above the logo and time
- [ ] Remove drop down icon
- [ ] Make pages and referrals/utm codes black (but keep them links so they stay clickable in the PDF)
- [ ] Fix Chrome icon
- [ ] Add `Generated on ...` before the date
- [ ] Make the string of the generated date a bit more gray (it's less important)

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/121525191-a0ca9400-ca2a-11eb-9f10-9f50720c6be3.png"></kbd>

**Comment by jibsaramnim** [comment]
@adriaanvanrossum regarding the last `more horizontal space` arrows shown in the screenshot, do you mean I should make the entire dashboard wider than normal for the print version? Or do you mean more (vertical) space between the dashboard data and the footer?

**Comment by adriaanvanrossum** [comment]
Sorry. Vertical space!

**Comment by adriaanvanrossum** [comment]
Done!

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/1079135/140077303-4c69edb4-585e-47e6-8928-4fe4d4f87a97.png">
